import {useState} from "react";

export default function useWss() {
    const [data, setData] = useState(fake)
    return {data, isLoading: false, isLoaded:true}
}

const fake = {
    "latitude": 33.7753208,
    "longitude": -84.4085083,
    "timezone": "America/New_York",
    "currently": {
        "time": 1558528480,
        "summary": "Partly Cloudy",
        "icon": "partly-cloudy-day",
        "nearestStormDistance": 0,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 74.32,
        "apparentTemperature": 74.72,
        "dewPoint": 63.69,
        "humidity": 0.7,
        "pressure": 1017.95,
        "windSpeed": 0.74,
        "windGust": 4.71,
        "windBearing": 247,
        "cloudCover": 0.32,
        "uvIndex": 1,
        "visibility": 5.56,
        "ozone": 285.72
    },
    "minutely": {
        "summary": "Partly cloudy for the hour.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1558528440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558528980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1558529460,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.01,
                "precipType": "rain"
            },
            {
                "time": 1558529520,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.01,
                "precipType": "rain"
            },
            {
                "time": 1558529580,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.02,
                "precipType": "rain"
            },
            {
                "time": 1558529640,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.03,
                "precipType": "rain"
            },
            {
                "time": 1558529700,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.05,
                "precipType": "rain"
            },
            {
                "time": 1558529760,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.08,
                "precipType": "rain"
            },
            {
                "time": 1558529820,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.1,
                "precipType": "rain"
            },
            {
                "time": 1558529880,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.14,
                "precipType": "rain"
            },
            {
                "time": 1558529940,
                "precipIntensity": 0.002,
                "precipIntensityError": 0,
                "precipProbability": 0.17,
                "precipType": "rain"
            },
            {
                "time": 1558530000,
                "precipIntensity": 0.002,
                "precipIntensityError": 0.001,
                "precipProbability": 0.22,
                "precipType": "rain"
            },
            {
                "time": 1558530060,
                "precipIntensity": 0.002,
                "precipIntensityError": 0.001,
                "precipProbability": 0.25,
                "precipType": "rain"
            },
            {
                "time": 1558530120,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.29,
                "precipType": "rain"
            },
            {
                "time": 1558530180,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.33,
                "precipType": "rain"
            },
            {
                "time": 1558530240,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.35,
                "precipType": "rain"
            },
            {
                "time": 1558530300,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.4,
                "precipType": "rain"
            },
            {
                "time": 1558530360,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.43,
                "precipType": "rain"
            },
            {
                "time": 1558530420,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.46,
                "precipType": "rain"
            },
            {
                "time": 1558530480,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.46,
                "precipType": "rain"
            },
            {
                "time": 1558530540,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.49,
                "precipType": "rain"
            },
            {
                "time": 1558530600,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.49,
                "precipType": "rain"
            },
            {
                "time": 1558530660,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.5,
                "precipType": "rain"
            },
            {
                "time": 1558530720,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.51,
                "precipType": "rain"
            },
            {
                "time": 1558530780,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.49,
                "precipType": "rain"
            },
            {
                "time": 1558530840,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.49,
                "precipType": "rain"
            },
            {
                "time": 1558530900,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.49,
                "precipType": "rain"
            },
            {
                "time": 1558530960,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.48,
                "precipType": "rain"
            },
            {
                "time": 1558531020,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.47,
                "precipType": "rain"
            },
            {
                "time": 1558531080,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.45,
                "precipType": "rain"
            },
            {
                "time": 1558531140,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.45,
                "precipType": "rain"
            },
            {
                "time": 1558531200,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.43,
                "precipType": "rain"
            },
            {
                "time": 1558531260,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.43,
                "precipType": "rain"
            },
            {
                "time": 1558531320,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.41,
                "precipType": "rain"
            },
            {
                "time": 1558531380,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.4,
                "precipType": "rain"
            },
            {
                "time": 1558531440,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.4,
                "precipType": "rain"
            },
            {
                "time": 1558531500,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.39,
                "precipType": "rain"
            },
            {
                "time": 1558531560,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.38,
                "precipType": "rain"
            },
            {
                "time": 1558531620,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.37,
                "precipType": "rain"
            },
            {
                "time": 1558531680,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.36,
                "precipType": "rain"
            },
            {
                "time": 1558531740,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.36,
                "precipType": "rain"
            },
            {
                "time": 1558531800,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.001,
                "precipProbability": 0.36,
                "precipType": "rain"
            },
            {
                "time": 1558531860,
                "precipIntensity": 0.002,
                "precipIntensityError": 0.001,
                "precipProbability": 0.36,
                "precipType": "rain"
            },
            {
                "time": 1558531920,
                "precipIntensity": 0.002,
                "precipIntensityError": 0.001,
                "precipProbability": 0.35,
                "precipType": "rain"
            },
            {
                "time": 1558531980,
                "precipIntensity": 0.002,
                "precipIntensityError": 0.001,
                "precipProbability": 0.35,
                "precipType": "rain"
            },
            {
                "time": 1558532040,
                "precipIntensity": 0.002,
                "precipIntensityError": 0.001,
                "precipProbability": 0.33,
                "precipType": "rain"
            }
        ]
    },
    "hourly": {
        "summary": "Partly cloudy later this morning.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1558526400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.01,
                "apparentTemperature": 72.53,
                "dewPoint": 64.4,
                "humidity": 0.77,
                "pressure": 1017.67,
                "windSpeed": 0.36,
                "windGust": 4.35,
                "windBearing": 283,
                "cloudCover": 0.34,
                "uvIndex": 1,
                "visibility": 3.37,
                "ozone": 285.9
            },
            {
                "time": 1558530000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0019,
                "precipProbability": 0.51,
                "precipType": "rain",
                "temperature": 76.01,
                "apparentTemperature": 76.32,
                "dewPoint": 62.96,
                "humidity": 0.64,
                "pressure": 1018.15,
                "windSpeed": 1.07,
                "windGust": 4.96,
                "windBearing": 239,
                "cloudCover": 0.3,
                "uvIndex": 2,
                "visibility": 7.15,
                "ozone": 285.59
            },
            {
                "time": 1558533600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.002,
                "precipProbability": 0.36,
                "precipType": "rain",
                "temperature": 80.1,
                "apparentTemperature": 81.13,
                "dewPoint": 61.07,
                "humidity": 0.52,
                "pressure": 1018.41,
                "windSpeed": 2.14,
                "windGust": 7.96,
                "windBearing": 195,
                "cloudCover": 0.14,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 285.38
            },
            {
                "time": 1558537200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 83.47,
                "apparentTemperature": 83.66,
                "dewPoint": 60.27,
                "humidity": 0.46,
                "pressure": 1018.75,
                "windSpeed": 3.7,
                "windGust": 10.38,
                "windBearing": 193,
                "cloudCover": 0.04,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 285.16
            },
            {
                "time": 1558540800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 85.96,
                "apparentTemperature": 85.96,
                "dewPoint": 59.51,
                "humidity": 0.41,
                "pressure": 1018.8,
                "windSpeed": 5.27,
                "windGust": 11.96,
                "windBearing": 191,
                "cloudCover": 0.04,
                "uvIndex": 10,
                "visibility": 10,
                "ozone": 285.15
            },
            {
                "time": 1558544400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 87.48,
                "apparentTemperature": 87.48,
                "dewPoint": 58.58,
                "humidity": 0.38,
                "pressure": 1018.85,
                "windSpeed": 7.03,
                "windGust": 13,
                "windBearing": 189,
                "cloudCover": 0.03,
                "uvIndex": 11,
                "visibility": 10,
                "ozone": 285.16
            },
            {
                "time": 1558548000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0019,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 88.89,
                "apparentTemperature": 88.89,
                "dewPoint": 58.11,
                "humidity": 0.36,
                "pressure": 1018.88,
                "windSpeed": 7.78,
                "windGust": 13.38,
                "windBearing": 191,
                "cloudCover": 0.04,
                "uvIndex": 11,
                "visibility": 10,
                "ozone": 285.12
            },
            {
                "time": 1558551600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.002,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 89.92,
                "apparentTemperature": 89.92,
                "dewPoint": 57.99,
                "humidity": 0.34,
                "pressure": 1018.66,
                "windSpeed": 8.51,
                "windGust": 13.34,
                "windBearing": 191,
                "cloudCover": 0.1,
                "uvIndex": 10,
                "visibility": 10,
                "ozone": 284.91
            },
            {
                "time": 1558555200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0014,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 90.48,
                "apparentTemperature": 90.48,
                "dewPoint": 57.79,
                "humidity": 0.33,
                "pressure": 1018.66,
                "windSpeed": 8.83,
                "windGust": 12.89,
                "windBearing": 191,
                "cloudCover": 0.16,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 284.68
            },
            {
                "time": 1558558800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0011,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 90.68,
                "apparentTemperature": 90.68,
                "dewPoint": 57.38,
                "humidity": 0.33,
                "pressure": 1018.57,
                "windSpeed": 8.59,
                "windGust": 12,
                "windBearing": 192,
                "cloudCover": 0.2,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 284.56
            },
            {
                "time": 1558562400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 90.58,
                "apparentTemperature": 90.58,
                "dewPoint": 58.2,
                "humidity": 0.34,
                "pressure": 1018.29,
                "windSpeed": 7.8,
                "windGust": 11.75,
                "windBearing": 195,
                "cloudCover": 0.21,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 284.44
            },
            {
                "time": 1558566000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 89.32,
                "apparentTemperature": 89.32,
                "dewPoint": 58.66,
                "humidity": 0.36,
                "pressure": 1018.38,
                "windSpeed": 6.53,
                "windGust": 10.88,
                "windBearing": 201,
                "cloudCover": 0.21,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 284.31
            },
            {
                "time": 1558569600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 87.51,
                "apparentTemperature": 87.51,
                "dewPoint": 59.35,
                "humidity": 0.39,
                "pressure": 1018.61,
                "windSpeed": 5.52,
                "windGust": 9.62,
                "windBearing": 196,
                "cloudCover": 0.15,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.21
            },
            {
                "time": 1558573200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0011,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 84.63,
                "apparentTemperature": 84.63,
                "dewPoint": 59.48,
                "humidity": 0.43,
                "pressure": 1019.13,
                "windSpeed": 4.49,
                "windGust": 7.69,
                "windBearing": 186,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.22
            },
            {
                "time": 1558576800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 82.62,
                "apparentTemperature": 82.94,
                "dewPoint": 60.19,
                "humidity": 0.47,
                "pressure": 1019.82,
                "windSpeed": 4.3,
                "windGust": 8.88,
                "windBearing": 177,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.35
            },
            {
                "time": 1558580400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 80.85,
                "apparentTemperature": 81.58,
                "dewPoint": 60.39,
                "humidity": 0.5,
                "pressure": 1020.35,
                "windSpeed": 3.84,
                "windGust": 8.81,
                "windBearing": 170,
                "cloudCover": 0.1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.36
            },
            {
                "time": 1558584000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 79.49,
                "apparentTemperature": 79.61,
                "dewPoint": 60.61,
                "humidity": 0.53,
                "pressure": 1020.58,
                "windSpeed": 4.27,
                "windGust": 9.83,
                "windBearing": 161,
                "cloudCover": 0.14,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.36
            },
            {
                "time": 1558587600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 78.28,
                "apparentTemperature": 78.4,
                "dewPoint": 60.86,
                "humidity": 0.55,
                "pressure": 1020.68,
                "windSpeed": 5.24,
                "windGust": 11.61,
                "windBearing": 149,
                "cloudCover": 0.19,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.27
            },
            {
                "time": 1558591200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.11,
                "apparentTemperature": 77.25,
                "dewPoint": 61.12,
                "humidity": 0.58,
                "pressure": 1020.78,
                "windSpeed": 6.12,
                "windGust": 13.81,
                "windBearing": 141,
                "cloudCover": 0.23,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.15
            },
            {
                "time": 1558594800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 75.54,
                "apparentTemperature": 75.68,
                "dewPoint": 61.38,
                "humidity": 0.62,
                "pressure": 1020.98,
                "windSpeed": 6.74,
                "windGust": 16.85,
                "windBearing": 144,
                "cloudCover": 0.22,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.03
            },
            {
                "time": 1558598400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.98,
                "apparentTemperature": 74.16,
                "dewPoint": 61.66,
                "humidity": 0.65,
                "pressure": 1021.24,
                "windSpeed": 7.27,
                "windGust": 20.05,
                "windBearing": 153,
                "cloudCover": 0.2,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283.94
            },
            {
                "time": 1558602000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.59,
                "apparentTemperature": 72.8,
                "dewPoint": 61.87,
                "humidity": 0.69,
                "pressure": 1021.58,
                "windSpeed": 7.53,
                "windGust": 21.57,
                "windBearing": 160,
                "cloudCover": 0.16,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283.94
            },
            {
                "time": 1558605600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.77,
                "apparentTemperature": 72.02,
                "dewPoint": 62.09,
                "humidity": 0.72,
                "pressure": 1022.07,
                "windSpeed": 7.49,
                "windGust": 20.84,
                "windBearing": 164,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.14
            },
            {
                "time": 1558609200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 70.95,
                "apparentTemperature": 71.23,
                "dewPoint": 62.32,
                "humidity": 0.74,
                "pressure": 1022.66,
                "windSpeed": 7.2,
                "windGust": 18.82,
                "windBearing": 167,
                "cloudCover": 0.05,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.52
            },
            {
                "time": 1558612800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.45,
                "apparentTemperature": 71.75,
                "dewPoint": 62.53,
                "humidity": 0.74,
                "pressure": 1023.18,
                "windSpeed": 6.84,
                "windGust": 16.31,
                "windBearing": 170,
                "cloudCover": 0.02,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 284.92
            },
            {
                "time": 1558616400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.95,
                "apparentTemperature": 74.25,
                "dewPoint": 62.79,
                "humidity": 0.68,
                "pressure": 1023.68,
                "windSpeed": 6.27,
                "windGust": 13.1,
                "windBearing": 175,
                "cloudCover": 0.05,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 285.46
            },
            {
                "time": 1558620000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.43,
                "apparentTemperature": 77.76,
                "dewPoint": 63.07,
                "humidity": 0.61,
                "pressure": 1024.12,
                "windSpeed": 5.6,
                "windGust": 9.29,
                "windBearing": 179,
                "cloudCover": 0.13,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 286.03
            },
            {
                "time": 1558623600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 80.53,
                "apparentTemperature": 81.96,
                "dewPoint": 63.33,
                "humidity": 0.56,
                "pressure": 1024.25,
                "windSpeed": 5.07,
                "windGust": 6.35,
                "windBearing": 184,
                "cloudCover": 0.18,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 286.39
            },
            {
                "time": 1558627200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 83.34,
                "apparentTemperature": 84.56,
                "dewPoint": 63.46,
                "humidity": 0.51,
                "pressure": 1023.93,
                "windSpeed": 4.77,
                "windGust": 5.22,
                "windBearing": 186,
                "cloudCover": 0.18,
                "uvIndex": 9,
                "visibility": 10,
                "ozone": 286.64
            },
            {
                "time": 1558630800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 85.47,
                "apparentTemperature": 86.6,
                "dewPoint": 63.48,
                "humidity": 0.48,
                "pressure": 1023.34,
                "windSpeed": 4.61,
                "windGust": 4.98,
                "windBearing": 187,
                "cloudCover": 0.17,
                "uvIndex": 10,
                "visibility": 10,
                "ozone": 286.74
            },
            {
                "time": 1558634400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 87.56,
                "apparentTemperature": 88.6,
                "dewPoint": 63.33,
                "humidity": 0.45,
                "pressure": 1022.67,
                "windSpeed": 4.54,
                "windGust": 4.83,
                "windBearing": 190,
                "cloudCover": 0.14,
                "uvIndex": 11,
                "visibility": 10,
                "ozone": 286.53
            },
            {
                "time": 1558638000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0019,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 89.01,
                "apparentTemperature": 89.91,
                "dewPoint": 62.95,
                "humidity": 0.42,
                "pressure": 1021.96,
                "windSpeed": 4.57,
                "windGust": 4.76,
                "windBearing": 197,
                "cloudCover": 0.22,
                "uvIndex": 9,
                "visibility": 10,
                "ozone": 285.89
            },
            {
                "time": 1558641600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0068,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 89.81,
                "apparentTemperature": 90.52,
                "dewPoint": 62.47,
                "humidity": 0.4,
                "pressure": 1021.2,
                "windSpeed": 4.56,
                "windGust": 4.86,
                "windBearing": 213,
                "cloudCover": 0.33,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 285.01
            },
            {
                "time": 1558645200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0126,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 89.89,
                "apparentTemperature": 90.5,
                "dewPoint": 62.24,
                "humidity": 0.4,
                "pressure": 1020.61,
                "windSpeed": 4.58,
                "windGust": 4.84,
                "windBearing": 220,
                "cloudCover": 0.41,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 284.44
            },
            {
                "time": 1558648800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0169,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 89.48,
                "apparentTemperature": 90.17,
                "dewPoint": 62.48,
                "humidity": 0.41,
                "pressure": 1020.3,
                "windSpeed": 4.39,
                "windGust": 4.65,
                "windBearing": 222,
                "cloudCover": 0.46,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 284.41
            },
            {
                "time": 1558652400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0194,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 88.38,
                "apparentTemperature": 89.27,
                "dewPoint": 62.98,
                "humidity": 0.43,
                "pressure": 1020.2,
                "windSpeed": 4.14,
                "windGust": 4.52,
                "windBearing": 220,
                "cloudCover": 0.49,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 284.66
            },
            {
                "time": 1558656000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0177,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 86.5,
                "apparentTemperature": 87.6,
                "dewPoint": 63.45,
                "humidity": 0.46,
                "pressure": 1020.22,
                "windSpeed": 3.75,
                "windGust": 4.41,
                "windBearing": 219,
                "cloudCover": 0.49,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.06
            },
            {
                "time": 1558659600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0099,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 84.16,
                "apparentTemperature": 85.48,
                "dewPoint": 63.84,
                "humidity": 0.51,
                "pressure": 1020.45,
                "windSpeed": 3.26,
                "windGust": 4.41,
                "windBearing": 204,
                "cloudCover": 0.49,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.47
            },
            {
                "time": 1558663200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0026,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 81.63,
                "apparentTemperature": 83.2,
                "dewPoint": 64.2,
                "humidity": 0.56,
                "pressure": 1020.79,
                "windSpeed": 2.61,
                "windGust": 4.47,
                "windBearing": 218,
                "cloudCover": 0.46,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.13
            },
            {
                "time": 1558666800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 79.7,
                "apparentTemperature": 81.44,
                "dewPoint": 64.45,
                "humidity": 0.6,
                "pressure": 1021.04,
                "windSpeed": 2.16,
                "windGust": 4.61,
                "windBearing": 222,
                "cloudCover": 0.41,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.31
            },
            {
                "time": 1558670400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 78.27,
                "apparentTemperature": 78.76,
                "dewPoint": 64.58,
                "humidity": 0.63,
                "pressure": 1021.13,
                "windSpeed": 2.16,
                "windGust": 4.8,
                "windBearing": 186,
                "cloudCover": 0.33,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.08
            },
            {
                "time": 1558674000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.13,
                "apparentTemperature": 77.62,
                "dewPoint": 64.59,
                "humidity": 0.65,
                "pressure": 1021.13,
                "windSpeed": 2.22,
                "windGust": 5.03,
                "windBearing": 166,
                "cloudCover": 0.23,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.38
            },
            {
                "time": 1558677600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 76.07,
                "apparentTemperature": 76.55,
                "dewPoint": 64.51,
                "humidity": 0.68,
                "pressure": 1021.09,
                "windSpeed": 2.49,
                "windGust": 5.43,
                "windBearing": 215,
                "cloudCover": 0.14,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.13
            },
            {
                "time": 1558681200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 74.99,
                "apparentTemperature": 75.44,
                "dewPoint": 64.21,
                "humidity": 0.69,
                "pressure": 1020.88,
                "windSpeed": 2.77,
                "windGust": 6.08,
                "windBearing": 226,
                "cloudCover": 0.09,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.31
            },
            {
                "time": 1558684800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.68,
                "apparentTemperature": 74.1,
                "dewPoint": 63.81,
                "humidity": 0.71,
                "pressure": 1020.59,
                "windSpeed": 3.24,
                "windGust": 6.77,
                "windBearing": 235,
                "cloudCover": 0.04,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.8
            },
            {
                "time": 1558688400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.01,
                "apparentTemperature": 73.41,
                "dewPoint": 63.55,
                "humidity": 0.72,
                "pressure": 1020.5,
                "windSpeed": 3.65,
                "windGust": 7.3,
                "windBearing": 235,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.26
            },
            {
                "time": 1558692000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.75,
                "apparentTemperature": 73.16,
                "dewPoint": 63.65,
                "humidity": 0.73,
                "pressure": 1020.74,
                "windSpeed": 3.88,
                "windGust": 7.63,
                "windBearing": 241,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 286.89
            },
            {
                "time": 1558695600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.72,
                "apparentTemperature": 73.17,
                "dewPoint": 63.93,
                "humidity": 0.74,
                "pressure": 1021.16,
                "windSpeed": 4.13,
                "windGust": 7.85,
                "windBearing": 240,
                "cloudCover": 0.03,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 287.69
            },
            {
                "time": 1558699200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 74.11,
                "apparentTemperature": 74.57,
                "dewPoint": 64.24,
                "humidity": 0.71,
                "pressure": 1021.5,
                "windSpeed": 4.32,
                "windGust": 8,
                "windBearing": 228,
                "cloudCover": 0.04,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 288.2
            }
        ]
    },
    "daily": {
        "summary": "Light rain tomorrow, with high temperatures rising to 95°F on Tuesday.",
        "icon": "rain",
        "data": [
            {
                "time": 1558497600,
                "summary": "Partly cloudy in the morning.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1558521222,
                "sunsetTime": 1558571872,
                "moonPhase": 0.63,
                "precipIntensity": 0.0006,
                "precipIntensityMax": 0.002,
                "precipIntensityMaxTime": 1558551600,
                "precipProbability": 0.53,
                "precipType": "rain",
                "temperatureHigh": 90.68,
                "temperatureHighTime": 1558558800,
                "temperatureLow": 70.95,
                "temperatureLowTime": 1558609200,
                "apparentTemperatureHigh": 90.68,
                "apparentTemperatureHighTime": 1558558800,
                "apparentTemperatureLow": 71.23,
                "apparentTemperatureLowTime": 1558609200,
                "dewPoint": 61.52,
                "humidity": 0.56,
                "pressure": 1017.69,
                "windSpeed": 3.74,
                "windGust": 13.38,
                "windGustTime": 1558548000,
                "windBearing": 188,
                "cloudCover": 0.24,
                "uvIndex": 11,
                "uvIndexTime": 1558544400,
                "visibility": 7.33,
                "ozone": 285.36,
                "temperatureMin": 70.36,
                "temperatureMinTime": 1558519200,
                "temperatureMax": 90.68,
                "temperatureMaxTime": 1558558800,
                "apparentTemperatureMin": 71,
                "apparentTemperatureMinTime": 1558519200,
                "apparentTemperatureMax": 90.68,
                "apparentTemperatureMaxTime": 1558558800
            },
            {
                "time": 1558584000,
                "summary": "Partly cloudy starting in the afternoon.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1558607590,
                "sunsetTime": 1558658315,
                "moonPhase": 0.66,
                "precipIntensity": 0.0037,
                "precipIntensityMax": 0.0194,
                "precipIntensityMaxTime": 1558652400,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperatureHigh": 89.89,
                "temperatureHighTime": 1558645200,
                "temperatureLow": 72.72,
                "temperatureLowTime": 1558695600,
                "apparentTemperatureHigh": 90.52,
                "apparentTemperatureHighTime": 1558641600,
                "apparentTemperatureLow": 73.16,
                "apparentTemperatureLowTime": 1558692000,
                "dewPoint": 62.62,
                "humidity": 0.55,
                "pressure": 1021.77,
                "windSpeed": 4.65,
                "windGust": 21.57,
                "windGustTime": 1558602000,
                "windBearing": 179,
                "cloudCover": 0.25,
                "uvIndex": 11,
                "uvIndexTime": 1558634400,
                "visibility": 10,
                "ozone": 285.14,
                "temperatureMin": 70.95,
                "temperatureMinTime": 1558609200,
                "temperatureMax": 89.89,
                "temperatureMaxTime": 1558645200,
                "apparentTemperatureMin": 71.23,
                "apparentTemperatureMinTime": 1558609200,
                "apparentTemperatureMax": 90.52,
                "apparentTemperatureMaxTime": 1558641600
            },
            {
                "time": 1558670400,
                "summary": "Partly cloudy starting in the afternoon, continuing until evening.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1558693960,
                "sunsetTime": 1558744756,
                "moonPhase": 0.69,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0002,
                "precipIntensityMaxTime": 1558710000,
                "precipProbability": 0.05,
                "precipType": "rain",
                "temperatureHigh": 91.69,
                "temperatureHighTime": 1558728000,
                "temperatureLow": 74,
                "temperatureLowTime": 1558778400,
                "apparentTemperatureHigh": 92.79,
                "apparentTemperatureHighTime": 1558728000,
                "apparentTemperatureLow": 74.58,
                "apparentTemperatureLowTime": 1558778400,
                "dewPoint": 64.03,
                "humidity": 0.56,
                "pressure": 1020.41,
                "windSpeed": 3.29,
                "windGust": 8.22,
                "windGustTime": 1558706400,
                "windBearing": 260,
                "cloudCover": 0.19,
                "uvIndex": 11,
                "uvIndexTime": 1558717200,
                "visibility": 10,
                "ozone": 289.06,
                "temperatureMin": 72.72,
                "temperatureMinTime": 1558695600,
                "temperatureMax": 91.69,
                "temperatureMaxTime": 1558728000,
                "apparentTemperatureMin": 73.16,
                "apparentTemperatureMinTime": 1558692000,
                "apparentTemperatureMax": 92.79,
                "apparentTemperatureMaxTime": 1558728000
            },
            {
                "time": 1558756800,
                "summary": "Partly cloudy in the evening.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1558780331,
                "sunsetTime": 1558831198,
                "moonPhase": 0.72,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1558796400,
                "precipProbability": 0.05,
                "precipType": "rain",
                "temperatureHigh": 94.62,
                "temperatureHighTime": 1558814400,
                "temperatureLow": 75.6,
                "temperatureLowTime": 1558864800,
                "apparentTemperatureHigh": 94.75,
                "apparentTemperatureHighTime": 1558814400,
                "apparentTemperatureLow": 75.86,
                "apparentTemperatureLowTime": 1558864800,
                "dewPoint": 63.46,
                "humidity": 0.53,
                "pressure": 1019.46,
                "windSpeed": 3.33,
                "windGust": 7.99,
                "windGustTime": 1558800000,
                "windBearing": 292,
                "cloudCover": 0.07,
                "uvIndex": 10,
                "uvIndexTime": 1558803600,
                "visibility": 10,
                "ozone": 297.92,
                "temperatureMin": 74,
                "temperatureMinTime": 1558778400,
                "temperatureMax": 94.62,
                "temperatureMaxTime": 1558814400,
                "apparentTemperatureMin": 74.58,
                "apparentTemperatureMinTime": 1558778400,
                "apparentTemperatureMax": 94.75,
                "apparentTemperatureMaxTime": 1558814400
            },
            {
                "time": 1558843200,
                "summary": "Partly cloudy in the morning.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1558866704,
                "sunsetTime": 1558917638,
                "moonPhase": 0.75,
                "precipIntensity": 0,
                "precipIntensityMax": 0.0002,
                "precipIntensityMaxTime": 1558861200,
                "precipProbability": 0,
                "temperatureHigh": 95.22,
                "temperatureHighTime": 1558900800,
                "temperatureLow": 75.62,
                "temperatureLowTime": 1558947600,
                "apparentTemperatureHigh": 95.22,
                "apparentTemperatureHighTime": 1558900800,
                "apparentTemperatureLow": 75.71,
                "apparentTemperatureLowTime": 1558947600,
                "dewPoint": 60.41,
                "humidity": 0.45,
                "pressure": 1019.03,
                "windSpeed": 4.36,
                "windGust": 11.36,
                "windGustTime": 1558904400,
                "windBearing": 308,
                "cloudCover": 0.18,
                "uvIndex": 11,
                "uvIndexTime": 1558893600,
                "visibility": 10,
                "ozone": 300.5,
                "temperatureMin": 75.6,
                "temperatureMinTime": 1558864800,
                "temperatureMax": 95.22,
                "temperatureMaxTime": 1558900800,
                "apparentTemperatureMin": 75.86,
                "apparentTemperatureMinTime": 1558864800,
                "apparentTemperatureMax": 95.22,
                "apparentTemperatureMaxTime": 1558900800
            },
            {
                "time": 1558929600,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1558953078,
                "sunsetTime": 1559004078,
                "moonPhase": 0.78,
                "precipIntensity": 0,
                "precipIntensityMax": 0.0002,
                "precipIntensityMaxTime": 1558994400,
                "precipProbability": 0,
                "temperatureHigh": 95.22,
                "temperatureHighTime": 1558987200,
                "temperatureLow": 74.31,
                "temperatureLowTime": 1559037600,
                "apparentTemperatureHigh": 95.22,
                "apparentTemperatureHighTime": 1558987200,
                "apparentTemperatureLow": 74.31,
                "apparentTemperatureLowTime": 1559037600,
                "dewPoint": 59.52,
                "humidity": 0.44,
                "pressure": 1016.64,
                "windSpeed": 4.63,
                "windGust": 16.5,
                "windGustTime": 1559012400,
                "windBearing": 282,
                "cloudCover": 0.64,
                "uvIndex": 7,
                "uvIndexTime": 1558983600,
                "visibility": 10,
                "ozone": 290.36,
                "temperatureMin": 75.62,
                "temperatureMinTime": 1558947600,
                "temperatureMax": 95.22,
                "temperatureMaxTime": 1558987200,
                "apparentTemperatureMin": 75.71,
                "apparentTemperatureMinTime": 1558947600,
                "apparentTemperatureMax": 95.22,
                "apparentTemperatureMaxTime": 1558987200
            },
            {
                "time": 1559016000,
                "summary": "Overcast throughout the day.",
                "icon": "cloudy",
                "sunriseTime": 1559039454,
                "sunsetTime": 1559090517,
                "moonPhase": 0.81,
                "precipIntensity": 0,
                "precipIntensityMax": 0.0001,
                "precipIntensityMaxTime": 1559084400,
                "precipProbability": 0,
                "temperatureHigh": 95.43,
                "temperatureHighTime": 1559077200,
                "temperatureLow": 78.99,
                "temperatureLowTime": 1559127600,
                "apparentTemperatureHigh": 95.43,
                "apparentTemperatureHighTime": 1559077200,
                "apparentTemperatureLow": 79.17,
                "apparentTemperatureLowTime": 1559127600,
                "dewPoint": 59.51,
                "humidity": 0.43,
                "pressure": 1013.44,
                "windSpeed": 4.64,
                "windGust": 19.54,
                "windGustTime": 1559034000,
                "windBearing": 246,
                "cloudCover": 0.97,
                "uvIndex": 5,
                "uvIndexTime": 1559059200,
                "visibility": 10,
                "ozone": 295.54,
                "temperatureMin": 74.31,
                "temperatureMinTime": 1559037600,
                "temperatureMax": 95.43,
                "temperatureMaxTime": 1559077200,
                "apparentTemperatureMin": 74.31,
                "apparentTemperatureMinTime": 1559037600,
                "apparentTemperatureMax": 95.43,
                "apparentTemperatureMaxTime": 1559077200
            },
            {
                "time": 1559102400,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1559125831,
                "sunsetTime": 1559176956,
                "moonPhase": 0.84,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0006,
                "precipIntensityMaxTime": 1559142000,
                "precipProbability": 0.04,
                "precipType": "rain",
                "temperatureHigh": 94.02,
                "temperatureHighTime": 1559160000,
                "temperatureLow": 73.18,
                "temperatureLowTime": 1559214000,
                "apparentTemperatureHigh": 94.02,
                "apparentTemperatureHighTime": 1559160000,
                "apparentTemperatureLow": 73.59,
                "apparentTemperatureLowTime": 1559214000,
                "dewPoint": 59.47,
                "humidity": 0.42,
                "pressure": 1011.6,
                "windSpeed": 8.49,
                "windGust": 19.75,
                "windGustTime": 1559185200,
                "windBearing": 220,
                "cloudCover": 0.7,
                "uvIndex": 9,
                "uvIndexTime": 1559149200,
                "visibility": 10,
                "ozone": 290.03,
                "temperatureMin": 78.99,
                "temperatureMinTime": 1559127600,
                "temperatureMax": 94.02,
                "temperatureMaxTime": 1559160000,
                "apparentTemperatureMin": 79.17,
                "apparentTemperatureMinTime": 1559127600,
                "apparentTemperatureMax": 94.02,
                "apparentTemperatureMaxTime": 1559160000
            }
        ]
    },
    "flags": {
        "sources": [
            "nearest-precip",
            "nwspa",
            "cmc",
            "gfs",
            "hrrr",
            "icon",
            "isd",
            "madis",
            "nam",
            "sref",
            "darksky"
        ],
        "nearest-station": 1.046,
        "units": "us"
    },
    "offset": -4
}